version: '3'

services:

  nginx:
    image: nginx:latest
    # image: tutum/nginx
    ports:
      - "8257:80"
    links: 
      - php7
    volumes:
      - ./backend:/application/public
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      # - ./docker/nginx/default:/etc/nginx/sites-available/default
      # - ./docker/nginx/default:/etc/nginx/sites-enabled/default
      
      - ./docker/nginx/logs/nginx-access.log:/var/log/nginx/access.log
      - ./docker/nginx/logs/nginx-error.log:/var/log/nginx/error.log

  php7:
    # container_name: php7
    environment:
      TZ: "Asia/Yekaterinburg"
    build: ./docker/php7
    ports: 
      - "9257:9000"
    volumes:
      - ./backend:/application/public
    depends_on: 
      - mysql

  mysql:
    image: mysql:5.7
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=forge
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456
    ports:
      - "3257:3306"
